
# Generated by Django 1.11.20 on 2019-03-14 19:08


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_twitter', '0001_initial'),
    ]

    operations = [
        # Rename Fields
        migrations.RenameField('TwitterRecentEntries', 'twitter_user', 'twitter_url'),
        migrations.RenameField('TwitterRecentEntries', 'count', 'tweet_limit'),

        # Remove Deprecated Fields
        migrations.RemoveField('TwitterRecentEntries', 'link_hint'),
        migrations.RemoveField('TwitterRecentEntries', 'twitter_id'),

        # Rename Model TwitterRecentEntries > TwitterTimeline
        migrations.RenameModel('TwitterRecentEntries', 'TwitterTimeline'),

        # Remove Twitter Search
        migrations.DeleteModel('TwitterSearch'),
    ]

