# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 19:08
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterTimeline',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_twitter_twittertimeline', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=75, null=True, verbose_name='title')),
                ('twitter_url', models.CharField(help_text='Enter a Twitter URL (see https://publish.twitter.com) e.g. <br><ol><li>A collection: https://twitter.com/TwitterDev/timelines/539487832448843776</li><li>A tweet: https://twitter.com/Interior/status/463440424141459456</li><li>A profile: https://twitter.com/TwitterDev</li><li>A list: https://twitter.com/TwitterDev/lists/national-parks</li><li>A moment: https://twitter.com/i/moments/625792726546558977</li><li>A likes timeline: https://twitter.com/TwitterDev/likes</li></ol>', max_length=512, verbose_name='twitter url')),
                ('tweet_limit', models.PositiveSmallIntegerField(blank=True, help_text='Number of entries to display', null=True, verbose_name='count')),
                ('width', models.PositiveSmallIntegerField(blank=True, help_text='Width in pixels', null=True, verbose_name='width')),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='Height in pixels', null=True, verbose_name='height')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=50, verbose_name='select theme')),
                ('link_color', colorfield.fields.ColorField(blank=True, default='#2B7BB9', max_length=18, null=True)),
                ('show_replies', models.BooleanField(default=False, verbose_name='Show Tweet Replies')),
                ('chrome', models.CharField(blank=True, max_length=512, null=True, verbose_name='Control the frame around the linear timeline')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='twitterrecententries',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='twittersearch',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='TwitterRecentEntries',
        ),
        migrations.DeleteModel(
            name='TwitterSearch',
        ),
    ]
